### PR TITLE
Add install options

### LINKED ISSUE #7: Add option to run a different install command
Hi, thanks again for creating install-changed! It's helped me a lot in everyday productivity.

The only issue I'm having with my new flow is that sometimes the `npm install` command that this runs changes `package-lock.json` and I end up with unexpected changed file in my repo.

For this purpose, there's [`npm ci`](https://docs.npmjs.com/cli/ci.html) which installs from the lockfile, is potentially faster, and doesn't change package-lock.json. Could you add an option to enable running `npm ci` instead of `npm install` if the `package.json` file is changed?

### PR DESCRIPTION
**Pull request by thdk**
'hashFileName' and 'command' can now be specified for both cli and api version.

install-changed --command="npm ci" --hashFileName=.packagehash

Both api and cli version of code now have these options.

Fixes ninesalt/install-changed#7

If the review is ok, I can update the readme with these new features.

### CODE REVIEW

**Comment by thdk** [comment]
@ninesalt just in case you forgot about his PR ;) If you are busy with other stuff, never mind this bump :)

**Comment by ninesalt** [comment]
Sorry for the late reply. I looked this over and I have a few comments. I don't think implementing a CLI parser from scratch is the correct way to go here. The original objective was for the package to be as simple as possible and adding a CLI parser adds maintainability overhead. Suggestion: check an existing npm package that already does CLI parsing well ([commander is easy](https://www.npmjs.com/package/commander#common-option-types-boolean-and-value))

I also don't understand the use for this fragment:

```
      // if command is a function, execute the function
      if (typeof command === 'function') {
        command()
      }
```

And I don't understand why you override `stdio` in the `execSync` function.

**Comment by thdk** [comment]
No problem, I'm glad with your reply and will update my PR with the requested changes.

**Comment by thdk** [comment]
I'll look into commander (I used minimist package before for this) for the cli argument parsing. The reason that I didn't use commander/minimist before is that install-changed had no dependencies so far so I though you might wanted to keep it like that. But if you don't mind a dependency, then it's indeed easier to use an existing package.

Regarding the code fragment "if command is a function, execute the function" I thought some users might want to implement/override the exec logic from this package instead of just providing the command. Now the install command (string) is executed using the childprocess execSync function (with hardcoded option as you have noticed) but others uses might want to use something else to run the command. (I'll remove this code for now, until someone would explicitly ask for it)

The reason for overriding stdio:
Here I was inspired by the fork of @ryanburnette (See commit here: https://github.com/ryanburnette/install-changed/commit/40998a32372487d5f660a11bbfef52037d1e5fe7) 

```
      execSync('npm ci --prefer-offline --color', {
        cwd: process.cwd(),
        stdio: ['inherit', 'inherit', 'inherit'],
        shell: true
      })
```
I don't know if we need cwd or shell option, maybe @ryanburnette wants to add his opinion here, but I believe overriding stdio with 'inherit' or [0,1,2] (see [docs](https://nodejs.org/api/child_process.html#child_process_options_stdio) is correct because it will pass all stdio streams to the parent process. Otherwise, the output of the install command is not visible in the parent process.

**Comment by thdk** [comment]
FYI: below is the output of running install-changed in my sample application. 
First run is with overriding stdio, second is without overriding.

```
> install-changed

package.json has been modified. Installing...

> core-js@2.6.11 postinstall D:\_Documents\Projects\app-navigation\node_modules\babel-runtime\node_modules\core-js  
> node -e "try{require('./postinstall')}catch(e){}"       

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!    

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock 
) is looking for a good job -)


> core-js@3.6.5 postinstall D:\_Documents\Projects\app-navigation\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"       


> core-js-pure@3.6.5 postinstall D:\_Documents\Projects\app-navigation\node_modules\core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"       

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\react-scripts\node_modules\fsevents):  
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported 
platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported 
platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\chokidar\node_modules\fsevents):       
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported 
platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1880 packages from 836 contributors in 219.903s     

59 packages are looking for funding
  run `npm fund` for details
```


```
> install-changed

package.json has been modified. Installing...
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\react-scripts\node_modules\fsevents):  
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported 
platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported 
platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\chokidar\node_modules\fsevents):       
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported 
platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```

As you can see, a lot of information is lost when we don't override stdio

**Comment by thdk** [comment]
@ninesalt have you seen my changes for this PR?

Let me know if you have thoughts or don't want to have these implemented after all.

**Comment by ninesalt** [comment]
Sorry I'm taking so long to merge this, I've been pretty busy these past few days . I reviewed your changes and they look okay but I've been meaning to try it out before I merge which I'll do this week.

**Comment by thdk** [comment]
@ninesalt this has not been released, correct?

**Pull request merged**
